<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNotEmail($email)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.email != :email')
            ->setParameter('email', $email)
            ->getQuery();
        return $qb->getResult();
    }
}
